### PR TITLE
Html query params and metadata documentation to api docs

### PR DESCRIPTION
**Pull request by quadrophobiac**

### CODE REVIEW

**Comment by quadrophobiac** [comment]
to fix #206

**Comment by Floppy** [comment]
I did these in the wrong order, sorry. @quadrophobiac do you want to resolve the merge conflicts so I don't get it wrong?

**Comment by quadrophobiac** [comment]
sure thing!

**Comment by quadrophobiac** [comment]
this is good to go @Floppy

**Pull request merged**
