### PR TITLE
Document with swagger 

### LINKED ISSUE #173: Document with Swagger
We should totally use Swagger to document the API. Maybe using https://github.com/ruby-grape and https://github.com/ruby-grape/grape-swagger. This would also have the added effect of decoupling the API code from the visualisation code.

### PR DESCRIPTION
**Pull request by quadrophobiac**
This PR fixes #173

Changes proposed in this pull request:

- [x] inclusion of Grape
- [x] refactor API functions to Grape Rack App, remaining functionality within Sinatra Rack App
- [x] use of Grape-Entity and Swagger to create API documentation

### CODE REVIEW

**Comment by quadrophobiac** [comment]
@Floppy  & @pezholio - I’m blocked on this issue and I need some pointers on what the hoped for outcome of using Grape to modularise Bothan was, because I think what I assumed would happen is not possible.

I had assumed that the ideal outcome would be utilising Grape to serve every existing REST endpoint (GET, POST etc.). With Grape serving up JSON at endpoints such as `root/metrics.json` the Sinatra app would be able to consume that JSON by pointing its views towards the JSON endpoint. The Sinatra app would become a client that reads and presents JSON from the Grape API to a GUI user, with the Grape API acting like a controller.
I was unable to accomplish this however - any effort using code such as
```
require 'open-uri'
data = open('http://localhost:9292/metrics.json')
```
Or
```
require 'rest-client'
response = RestClient.get('http://localhost:9292/metrics.json’)
```
...resulted in server time outs and thus no consumed JSON. Admittedly I’m not sure if I am missing something obvious here

So I’ve looked at the way that Grape was integrated into Octopub and it seems like there is repetition of logic (sic) when using Grape. For example the Dataset Controller sets an [instance variable of @datasets by looking up the Dataset Model](https://github.com/theodi/octopub/blob/master/app/controllers/datasets_controller.rb#L20).   
```
@datasets = Dataset.github_public.order(created_at: :desc)
```
Which is used for the datasets view [here](https://github.com/theodi/octopub/blob/master/app/views/datasets/_datasets.html.erb#L19)
And the Grape API makes its own separate call to/utilisation of the Datasets model in these [lines](https://github.com/theodi/octopub/blob/master/app/api/octopub/datasets/list.rb#L7-L8) 
```
get :datasets do
        datasets = ::Dataset.all.order(created_at: :desc)
```

Does that mean that the same will apply to the Sinatra app in Bothan: namely that the Sinatra App and the Grape API will be making their own separate calls to the models persisting the data to the MongoDB database? In other words rather than the Grape API acting as the sole controller there are two controllers, one per rack application in this case. I’ve included an example of what this would look like in this PR  - [see the way that the Grape API and the Sinatra App both avail of the same helper method](https://github.com/theodi/bothan/pull/291/commits/8aff095d534cc8af712d2bdf939081fe9ea759f3). 
I need feedback on this now because so much of the rest of the refactor hinges on which way Grape should be integrated into this Sinatra app. To me it seems like doing the above wouldn't result in much "decoupling (of) the API code from the visualisation code" but it would enable a swagger documented API

**Comment by quadrophobiac** [comment]
So I've pressed on with this - I think the shared helper method in the code pushed so far might be the exception. The original issue stated a benefit of 
>decoupling the API code from the visualisation code
most of the visualisations load the [JSON via jQuery](https://github.com/theodi/bothan/blob/master/lib/views/chart.erb#L45-L53) - am I right in presuming that they'll be able to call to the Grape endpoints once the refactor is complete?

**Comment by quadrophobiac** [comment]
So the bare bones of this addition are in place. Some changes can be made to the styling of the swagger documentation. Decision needed as to where to host this documentation on live sites.
Room for improvement: modularisation of the API, best practice use of Swagger. Will be working away on those tomorrow but would like to signal the readiness of this for a Code Review at this point as do not envision any further major rearrangements

**Comment by quadrophobiac** [comment]
@Floppy I'm not sure what is causing the DateWrangler failure in the specs so if you have advice on that that would also be cool

**Comment by quadrophobiac** [comment]
run the app `bundle exec rake`  
navigate to http://localhost:9292/api_documentation to have a look at the automatic api documentation

**Comment by quadrophobiac** [comment]
hey @Floppy - any thoughts on this PR? thanks, ste

**Comment by Floppy** [comment]
@quadrophobiac I'm checking this over now. I've done a couple of fixes to fix build failures, just chasing down the last one now.

**Comment by Floppy** [comment]
@quadrophobiac @olivierthereaux this is now merged, so Stephen's blog post can go out.

**Comment by olivierthereaux** [comment]
Thanks @Floppy! Will check with the team, might be too tight to get the blog post published before the holiday break though.

**Comment by quadrophobiac** [comment]
@Floppy I just saw this merge now! I forgot to change my contact address back from the @theodi email address so I was receiving 0 github notifications. Thanks so much for merging this!

**Pull request merged**
