### PR TITLE
Store title and description in metadata object

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by Floppy** [comment]
I think this could actually merge @pezholio - it handles the data storage aspect fine, just not display. Oh, no, I didn't write any documentation for it. That's why.

**Comment by pezholio** [comment]
Ah ha. I'll write some docs then merge this sucker 👍

**Comment by pezholio** [comment]
I've rebased against master too BTW

**Comment by pezholio** [comment]
Right. This is almost there. The only things we haven't got are locale setting (at the moment, it uses `en`) and description (which we need to get to handle HTML and Plotly views - as well as shadow root stuff). But I think this might be too much of a rabbit hole to get into on a Friday afternoon

**Pull request merged**
