### PR TITLE
Swagger documentation for post

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by Floppy** [comment]
@quadrophobiac this has conflicts in the README too, want to bring it up to date? Should I review and merge?

**Comment by quadrophobiac** [comment]
I can't recall why this was a PR, as I am not sure it's complete yet, there's still work to do to get it auto generating API docs with Swagger

**Comment by Floppy** [comment]
OK. I probably just opened it to look at the diff.

**Comment by Floppy** [comment]
Feel free to close it without merge if it's not ready yet. Up to you.

**Comment by quadrophobiac** [comment]
more work required on this before merge possible

**Pull request closed without merging**
