### PR TITLE
Acceptance tests html

### LINKED ISSUE #257: Write acceptance test/features for HTML user interactions
Current features do not mock "human-readable" user interaction with the service. Incorporation of functional capybara steps required.

### PR DESCRIPTION
**Pull request by quadrophobiac**
This PR is intended to fix #257. 
Changes proposed in this pull request:

- addition of some basic features for mocking user interactions, such at basic_auth login
- refactor of existing metadata feature to better approximate user interactions
- addition of dashboard features which require capybara-webkit to function due to the dashboard view relying on `/public/javascripts/dashboard.js` to render the dashboard as a user would encounter it
- change to the travis.yml to enable capybara-webkit (which has [QT dependencies](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit)) to run - **note** this has involved changing the `sudo` attribute to **required**, I'm uncertain if this is undesirable

### CODE REVIEW

**Comment by quadrophobiac** [comment]
So this has failed in a way I sort of figured it would `/home/travis/build/theodi/bothan/vendor/bundle/ruby/2.4.0/gems/capybara-webkit-1.14.0/bin/webkit_server failed to start. (Capybara::Webkit::ConnectionError)`
figure that some travis configuration is required, hopefully not related to webkits [QT dependency](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit)

**Comment by pezholio** [comment]
@quadrophobiac Have you tried Headless Chrome? https://robots.thoughtbot.com/headless-feature-specs-with-chrome

**Comment by quadrophobiac** [comment]
@pezholio - I have not, wanted to use the existing libraries in Bothan. I'm not sure what Capybara webkit was being used for prior to this but that's just my ignorance of ruby speaking

**Comment by quadrophobiac** [comment]
@pezholio I did a clean install of bothan on another machine, created a new branch and removed `capybara-webkit` and replaced it with `capybara`. 
All the tests ran fine so AFAICT capybara-webkit is not a prerequisite for extant Bothan code. 
I'm going to include the Headless Chrome within this PR and if it works then maybe Capybara Webkit can be removed from this repo altogether - the QT5.5 dependency of capybara-webkit always felt like way more overheads than was warranted so it'd be good to ditch that

**Comment by quadrophobiac** [comment]
Travis is now breaking due to `rvm use 2.4.1` and this is a known but unresolved issue, see here https://github.com/travis-ci/travis-ci/issues/7848

**Comment by quadrophobiac** [comment]
@pezholio the headless chrome method wasn't any less fraught in terms of travis errors to going back to webkit for now. 
This seems to be one resolution to the problem I encountered https://github.com/thoughtbot/capybara-webkit/issues/933, namely these additions to .travis.yml
```
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
script: xvfb-run bundle exec rake
```
but I don't yet know enough about travis to proceed

**Comment by quadrophobiac** [comment]
@Floppy I'm not sure if I've done something to cause this error but currently travis is failing here for this reason
```
Libraries missing for ruby-2.4.1: /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib,/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, stopping installation.
Gemset '' does not exist, 'rvm ruby-2.4.1 do rvm gemset create ' first, or append '--create'.
The command "rvm use 2.4.1 --install --binary --fuzzy" failed and exited with 2 during .
Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```
This has only shown up recently on this PR -  not on any other PRs using 2.4.1 for instance (https://github.com/theodi/bothan/pull/270). Is it possible I mucked something up committing the gemfile.lock in commit https://github.com/theodi/bothan/pull/269/commits/221ae1f956399d7066dcdb5d2665290f90730ee0?

**Comment by Floppy** [comment]
You have 'language' in the travis yml twice - once for Ruby, once for Obj-C. I think that should be an array at the very least, if it's even a thing that you can do.

**Comment by quadrophobiac** [comment]
Ok I've updated this PR's description to reflect all the changes made in this PR. The recommendations for running travis.yml from capybara-webki have resolve the CI issues initially raised by opening this PR as WiP. I'm now awaiting feedback on whether these proposed changes are OK to integrate

**Comment by quadrophobiac** [comment]
@Floppy if you have a chance could you give this the once over, if it's acceptable it'd unblock some other issues I could work on

**Comment by quadrophobiac** [comment]
Creating a heroku review app results in failure owing to the following 

```
An error occurred while installing commonmarker (0.16.8), and Bundler cannot
       continue.
 [ERROR]: cmake is required and not installed.
```

holding on merge until resolved

**Comment by quadrophobiac** [comment]
Creating a heroku review app results in failure owing to the following 

```
An error occurred while installing commonmarker (0.16.8), and Bundler cannot
       continue.
 [ERROR]: cmake is required and not installed.
```

holding on merge until resolved

**Comment by quadrophobiac** [comment]
@Floppy I don't understand why the review apps are failing and can't tell if it's unrelated to how viable merging this PR into live is - the PR where commonmarker was added to this repo was merged without issue so can you advise on what the proper git->heroku protocol is please?

**Comment by Floppy** [comment]
Ah, I think #267 was merged prematurely and I forgot to go back and fix the Heroku deployment. This is an outstanding blocker at the moment.

**Comment by Floppy** [comment]
For now, if things pass, they can merge into master. Then as soon as we get deployment running again, it'll all go live.

**Pull request merged**
